services:
  - type: web
    name: ttkpro
    runtime: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: ttkpro-data
      mountPath: /var/data
      sizeGB: 5
    envVars:
      - key: DB_HOST
        value: "127.0.0.1"
      - key: DB_USER
        value: ttkpro
      - key: DB_PASS
        value: ttkpro
      - key: DB_NAME
        value: ttkpro
      - key: MYSQL_ROOT_PASSWORD
        value: rootpass
      - key: MYSQL_DATADIR
        value: "/var/data/mysql"
